### ISSUE TITLE
Abstract away the row generation logic from file writers

### ISSUE THREAD

**Issue by not-ad-chaos** [acmpesuecc/creme-brulee#2]
Currently, row generation and writing to the DB happen at the same time, which makes it very tightly coupled with the file type we'll be writing to. For example, if we wanted to instead generate a json or a csv, we will have to write bespoke code for each format, as seen in `write_to_file` and `write_to_db`, this is also error prone as any changes will need to be replicated everywhere.

It would be nice to be able to specify the file format to `write_tables` and everything else is taken care for automatically.

```py
with MockDB(dbidx) as mdb:
    # writes a json
    mdb.init_tables().write_tables(MockDB.json).log_answer()
```

**Comment by rithulkamesh** [comment]
can i get assigned to this?

**Comment by not-ad-chaos** [comment]
!assign @rithulkamesh

**Comment by not-ad-chaos** [comment]
There has been a recession, this issue is now worth 800 points

**Comment by not-ad-chaos** [comment]
!deassign @rithulkamesh

**Comment by not-ad-chaos** [comment]
!assign @rithulkamesh 60

**Comment by not-ad-chaos** [comment]
!extend 30
